namespace RoomBuildingStarterKit.Editor
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using UnityEditor;
    using UnityEngine;

    /// <summary>
    /// The GenerateUIText class is used to generate UIText.cs by GameText.json.
    /// </summary>
    public class GenerateUIText
    {
        /// <summary>
        /// The script template.
        /// </summary>
        private static string scriptTemplate = 
@"// This file is auto generated by GenerateUIText.cs. Please don't modify it by hand.

namespace RoomBuildingStarterKit.Common
{{
    public enum UIText
    {{
{0}
    }}
}}
";
        /// <summary>
        /// Executes to generate UIText.cs.
        /// </summary>
        [MenuItem("Tools/Generate UIText")]
        public static void Generate()
        {
            var content = string.Empty;
#if UNITY_EDITOR
                content = File.ReadAllText($"{Application.dataPath}\\RoomBuildingStarterKit\\Assets\\Config\\GameText.json");
#else
                content = File.ReadAllText($"{Application.streamingAssetsPath}\\Data\\GameText.json");
#endif
            var texts = JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, string>>>(content);
            var strings = string.Join(",\r\n", texts.Keys.ToList().Select(s => "\t\t" + s).ToList());
            File.WriteAllText($"{Application.dataPath}\\RoomBuildingStarterKit\\Assets\\Scripts\\Common\\UIText.cs", string.Format(scriptTemplate, strings));
        }
    }
}
